logging:
  config: classpath:logback-base.xml

spring:
  application:
    name: PN-TEMPLATES-ENGINE

pn:
  env: # Runtime mode
    runtime: PROD
  templates-engine:
    parameterStoreCacheTTL: 10m
    urlResolverTimeout: 5s

templatesPath: "generated-templates-assets/templates"
defaultLanguage: IT
templates:
  notificationReceivedLegalFact:
    input:
      IT: "NotificationReceivedLegalFact/NotificationReceivedLegalFact.html"
      DE: "NotificationReceivedLegalFact/NotificationReceivedLegalFact_de.html"
      SL: "NotificationReceivedLegalFact/NotificationReceivedLegalFact_sl.html"
      FR: "NotificationReceivedLegalFact/NotificationReceivedLegalFact_fr.html"
  pecDeliveryWorkflowLegalFact:
    input:
      IT: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact.html"
      DE: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact_de.html"
      SL: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact_sl.html"
      FR: "PecDeliveryWorkflowLegalFact/PecDeliveryWorkflowLegalFact_fr.html"
  notificationViewedLegalFact:
    input:
      IT: "NotificationViewedLegalFact/NotificationViewedLegalFact.html"
      DE: "NotificationViewedLegalFact/NotificationViewedLegalFact_de.html"
      SL: "NotificationViewedLegalFact/NotificationViewedLegalFact_sl.html"
      FR: "NotificationViewedLegalFact/NotificationViewedLegalFact_fr.html"
  malfunctionLegalFact:
    input:
      IT: "MalfunctionLegalFact/MalfunctionLegalFact.html"
      DE: "MalfunctionLegalFact/MalfunctionLegalFact_de.html"
      SL: "MalfunctionLegalFact/MalfunctionLegalFact_sl.html"
      FR: "MalfunctionLegalFact/MalfunctionLegalFact_fr.html"
  notificationCancelledLegalFact:
    input:
      IT: "NotificationCancelledLegalFact/NotificationCancelledLegalFact.html"
      DE: "NotificationCancelledLegalFact/NotificationCancelledLegalFact_de.html"
      SL: "NotificationCancelledLegalFact/NotificationCancelledLegalFact_sl.html"
      FR: "NotificationCancelledLegalFact/NotificationCancelledLegalFact_fr.html"
  notificationAar:
    input:
      IT: "NotificationAAR_old/NotificationAAR_old.html"
      DE: "NotificationAAR_old/NotificationAAR_old_de.html"
      SL: "NotificationAAR_old/NotificationAAR_old_sl.html"
      FR: "NotificationAAR_old/NotificationAAR_old_fr.html"
    resolvers:
      senderLogoBase64:
        enabled: true
        bypassAllWithNull: true
        returnNullOnError: true
        whitelistEnabled: false
#        whitelistParameterStores:
#          - /pn-templates-engine/Whitelist1
#          - /pn-templates-engine/Whitelist2
  notificationAarRaddAlt:
    input:
      IT: "NotificationAAR_RADDalt_old/NotificationAAR_RADDalt_old.html"
      DE: "NotificationAAR_RADDalt_old/NotificationAAR_RADDalt_old_de.html"
      SL: "NotificationAAR_RADDalt_old/NotificationAAR_RADDalt_old_sl.html"
      FR: "NotificationAAR_RADDalt_old/NotificationAAR_RADDalt_old_fr.html"
    resolvers:
      senderLogoBase64:
        enabled: true
        bypassAllWithNull: true
        returnNullOnError: true
        whitelistEnabled: false
  analogDeliveryWorkflowFailureLegalFact:
    input:
      IT: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact.html"
      DE: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact_de.html"
      SL: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact_sl.html"
      FR: "AnalogDeliveryWorkflowFailureLegalFact/AnalogDeliveryWorkflowFailureLegalFact_fr.html"
  analogDeliveryWorkflowTimeoutLegalFact:
    input:
      IT: "AnalogDeliveryWorkflowTimeoutLegalFact/AnalogDeliveryWorkflowTimeoutLegalFact.html"
  notificationAarForEmailAnalog:
    input:
      IT: "NotificationAARForEMAILAnalog/NotificationAARForEMAILAnalog.html"
      DE: "NotificationAARForEMAILAnalog/NotificationAARForEMAILAnalog_de.html"
      SL: "NotificationAARForEMAILAnalog/NotificationAARForEMAILAnalog_sl.html"
      FR: "NotificationAARForEMAILAnalog/NotificationAARForEMAILAnalog_fr.html"
  notificationAarForEmailDigital:
    input:
      IT: "NotificationAARForEMAILDigital/NotificationAARForEMAILDigital.html"
      DE: "NotificationAARForEMAILDigital/NotificationAARForEMAILDigital_de.html"
      SL: "NotificationAARForEMAILDigital/NotificationAARForEMAILDigital_sl.html"
      FR: "NotificationAARForEMAILDigital/NotificationAARForEMAILDigital_fr.html"
  notificationAarForPec:
    input:
      IT: "NotificationAARForPEC/NotificationAARForPEC.html"
      DE: "NotificationAARForPEC/NotificationAARForPEC_de.html"
      SL: "NotificationAARForPEC/NotificationAARForPEC_sl.html"
      FR: "NotificationAARForPEC/NotificationAARForPEC_fr.html"
  notificationAarForSmsAnalog:
    input:
      IT: "NotificationAARForSMSAnalog/NotificationAARForSMSAnalog.txt"
  notificationAarForSmsDigital:
    input:
      IT: "NotificationAARForSMSDigital/NotificationAARForSMSDigital.txt"
  notificationAarForSubject:
    input:
      IT: "NotificationAARFor_Subject/NotificationAARFor_Subject.txt"
  mailVerificationCodeBody:
    input:
      IT: "Mail_VerificationCodeBody/Mail_VerificationCodeBody.html"
  pecVerificationCodeBody:
    input:
      IT: "PEC_VerificationCodeBody/PEC_VerificationCodeBody.html"
  pecVerificationCodeSubject:
    loadAsString: true
    input:
      IT: "PEC_VerificationCodeSubject/PEC_VerificationCodeSubject.txt"
  pecValidationContactsSuccessBody:
    input:
      IT: "PEC_ValidationContactsSuccessBody/PEC_ValidationContactsSuccessBody.html"
  pecValidationContactsRejectBody:
    input:
      IT: "PEC_ValidationContactsRejectBody/PEC_ValidationContactsRejectBody.html"
  smsVerificationCodeBody:
    loadAsString: true
    input:
      IT: "SMS_VerificationCodeBody/SMS_VerificationCodeBody.txt"
  mailVerificationCodeSubject:
    loadAsString: true
    input:
      IT: "Mail_VerificationCodeSubject/Mail_VerificationCodeSubject.txt"
  pecValidationContactsSuccessSubject:
    loadAsString: true
    input:
      IT: "PEC_ValidationContactsSuccessSubject/PEC_ValidationContactsSuccessSubject.txt"
  pecValidationContactsRejectSubject:
    loadAsString: true
    input:
      IT: "PEC_ValidationContactsRejectSubject/PEC_ValidationContactsRejectSubject.txt"
  notificationCceForEmail:
    input:
      IT: "NotificationCceForEmail/NotificationCceForEmail.html"
  notificationCceForSubject:
    loadAsString: true
    input:
      IT: "NotificationCceFor_Subject/NotificationCceFor_Subject.txt"